#! /bin/bash
docker run -it --rm \
  -e "USER=$USER" \
  -v $PWD/.cache/.ivy2:/root/.ivy2 \
  -v $PWD/.cache/.sbt:/root/.sbt \
  -v $PWD/.cache/.gcloud:/root/.config/gcloud \
  -v $PWD:/app \
  gcr.io/world-fishing-827/pipeline-scala $*
